Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/src/api_backend.rs, qoqo-qryd/src/api_devices.rs, qoqo-qryd/tests/integration/api_backend.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/api_backend.rs, roqoqo-qryd/src/api_devices.rs, roqoqo-qryd/tests/integration/api_backend.rs
Increasing coverage for release
=> increased test coverage

README.md, qoqo-qryd/README.md, roqoqo-qryd/README.md, userdoc/index.rst, userdoc/src/execution.rst, userdoc/src/installation.md, userdoc/src/introduction.rst, userdoc/src/qrydspecifics.rst, userdoc/src/webapi.rst
Documentation re-reviewed, syntax and typos updated.
=> Cosmetic updates to documentation

qoqo-qryd/examples/howto_webapi_qoqo.ipynb, qoqo-qryd/python_tests/requirements.txt, qoqo-qryd/python_tests/test_web_api.py, userdoc/src/qrydspecifics.rst
The yml that starts the tests in `python_tests` is missing.
=> Updated docs + python_tests with new signatures

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/tests/integration/api_backend.rs, qoqo-qryd/tests/integration/api_devices.rs, qoqo-qryd/tests/integration/operations.rs, qoqo-qryd/tests/integration/qryd_devices.rs, qoqo-qryd/tests/integration/simulator_backend.rs, roqoqo-qryd/Cargo.toml
Updating:
- pyo3 `0.17` -> `0.18`
- numpy `0.17` -> `0.18`
Renaming of pyo3's `cast_as` to `downcast`
=> Dependencies update

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/src/api_devices.rs, qoqo-qryd/src/qryd_devices.rs, qoqo-qryd/tests/integration/api_devices.rs, qoqo-qryd/tests/integration/qryd_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/api_devices.rs, roqoqo-qryd/src/qryd_devices.rs, roqoqo-qryd/tests/integration/api_devices.rs, roqoqo-qryd/tests/integration/qryd_devices.rs
This modifies the signature for the initialization of FirstDevice, QrydEmuTriangularDevice and QrydEmuSquareDevice so that the Python interface can accept floats as inputs of the phi-theta relation parameter.
=> Devices Initialization Signature Change + qoqo Update

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/docs/requirements.txt, qoqo-qryd/pyproject.toml, qoqo-qryd/python_tests/requirements.txt, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml
Contains dependency updates for qoqo 1.4
=> Update to qoqo 1.4

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/src/lib.rs, qoqo-qryd/src/pragma_operations.rs, qoqo-qryd/src/tweezer_devices.rs, qoqo-qryd/tests/integration/operations.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/api_backend.rs, roqoqo-qryd/src/pragma_operations.rs, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/api_backend.rs, roqoqo-qryd/tests/integration/pragma_operations.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
Adds TweezerDevice's `allowed_tweezer_shifts` data structure, 
Adds `PragmaSwitchDeviceLayout` operation.
Adds 3-qubit ops support for `APIBackend`.
=> Shift Structure + PragmaSwitchDeviceLayout

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/api_backend.rs
Substitutes any `PragmaRepeatedMeasurement` passed to `APIBackend.post_job()` into a set of `MeasureQubit` and a final `PragmaSetNumberOfMeasurements` operations.
=> PragmaRepeatedMeasurement Transformation

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/src/tweezer_devices.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/api_backend.rs, roqoqo-qryd/tests/integration/api_devices.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
* Modified `TweezerDevice`'s current layout to be optional
=> Optional TweezerDevice Current Layout

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, roqoqo-qryd/Cargo.toml
- Updated to qoqo 1.8.0-alpha.2
=> Qoqo 1.8.0a2 Support

.github/workflows/hqs-ci-test-rust-pyo3.yml, CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml
macos python 3.9 tests seem to always fail (usual mockito bug), so I've disabled them
=> 0.12 Full Release + Pyo3 0.20 Support

roqoqo-qryd/src/api_backend.rs, roqoqo-qryd/src/tweezer_devices.rs
This updates main with the new endpoints that were set in 0.11.8
=> Endpoints Correction

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/src/tweezer_devices.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
Adds `TweezerDevice.number_tweezer_positions()`.
Returns the total number of Tweezer positions in the current Layout.
=> TweezerDevice.number_tweezer_positions()

CHANGELOG.md, Cargo.lock, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/src/tweezer_devices.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
* Added `TweezerDevice.set_tweezers_per_row()`
* Modified `TweezerDevice.change_device()` for `PragmaSwitchDeviceLayout` to better reflect device constraints.
=> TweezerDevice.change_device() PragmaSwitchDeviceLayout Rework

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/api_devices.rs, roqoqo-qryd/tests/integration/simulator_backend.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
* Added gate set whitelist for `TweezerDevice` tweezer setters.
=> Tweezer Gate Set Whitelist 

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml
* Updated dependencies addressing security advisory
=> Security Update

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/src/tweezer_devices.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml
* Added `TweezerDevice.get_allow_reset()`
=> `allow_reset` Getter

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/tests/integration/api_backend.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/api_backend.rs, roqoqo-qryd/tests/integration/api_backend.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
* Substituted server mocking package `mockito` with `wiremock`
=> `mockito` -> `Wiremock`

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml
* Fixed 0.16.2 release dependencies issues
=> Relase Bugfix

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
* Modified `PragmaActiveReset` support's device name condition
=> Removed PragmaActiveReset device_name Check

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
* Modified `PragmaShiftQubitsTweezers` to functionally allow full-row shifts
=> Allow Full Row Shift via `PragmaShiftQubitsTweezers`

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, qoqo-qryd/qoqo_qryd/__init__.py, qoqo-qryd/src/emulator_devices.rs, qoqo-qryd/src/lib.rs, qoqo-qryd/src/tweezer_devices.rs, qoqo-qryd/tests/integration/emulator_devices.rs, qoqo-qryd/tests/integration/main.rs, qoqo-qryd/tests/integration/simulator_backend.rs, qoqo-qryd/tests/integration/tweezer_devices.rs, roqoqo-qryd/Cargo.toml, roqoqo-qryd/src/emulator_devices.rs, roqoqo-qryd/src/lib.rs, roqoqo-qryd/src/simulator_backend.rs, roqoqo-qryd/src/tweezer_devices.rs, roqoqo-qryd/tests/integration/emulator_devices.rs, roqoqo-qryd/tests/integration/main.rs, roqoqo-qryd/tests/integration/tweezer_devices.rs
=> `EmulatorDevice`

CHANGELOG.md, Cargo.lock, qoqo-qryd/Cargo.toml, qoqo-qryd/pyproject.toml, qoqo-qryd/qoqo_qryd/DEPENDENCIES, roqoqo-qryd/Cargo.toml
=> `0.20.0` Release Fix
